### ISSUE TITLE
Tooltip breaks page

### ISSUE THREAD

**Issue by Manderius** [timthedevguy/PrUnTools_Public#2]
When I select any other screen than my default one (I have 3 in total), the plugin does this:

![image](https://user-images.githubusercontent.com/6286058/150647756-5be0dfca-9407-490f-a1b2-adcf21db452d.png)

I am using plugin from the master branch with Tampermonkey v4.13 on the newest Chrome update. No errors are visible in the console.

**Comment by timthedevguy** [comment]
Thanks for the screenshot, I'll take a look today

**Comment by timthedevguy** [comment]
Fixed by [2862a7](https://github.com/timthedevguy/PrUnTools_Public/commit/2862a72e04233d4077ff210424bafb0ea9ed90b4)
